# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

setup_travis

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Certificates and Profiles
    match(
      readonly: true,
      type: "appstore",
      git_url: "https://github.com/mathocosta/fastlane-match.git"
    )

    increment_version_number

    # Build the app
    gym(
      scheme: "LearnContinuousIntegration",
      export_xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  lane :tests do
    scan(scheme: "LearnContinuousIntegration")
  end
end
